### ISSUE TITLE
Task does not fail on failed tests

### ISSUE THREAD

**Issue by arendjr** [ronaldlokers/grunt-casperjs#11]
When a Casper test fails, I believe the Grunt task should fail and thus block further execution of other tasks and let Grunt return a non-zero status code.

Currently this is not the case, but I have been able to achieve this effect with a simple patch. In the file lib/casperjs.js I replaced the puts function with the following version:

```
function puts(error, stdout, stderr) {
  grunt.log.write('\nRunning tests from "' + filepath + '":\n');
  grunt.log.write(stdout);

  if ( error !== null ) {
    callback(error);
  } else {
    if (stdout.indexOf("FAIL") > -1) {
        callback("Tests failed");
    } else {
        callback();
    }
  }
}
```

I'm not sure if this is really the best way to go about this, but please consider including this or a similar patch.

**Comment by Pascalmh** [comment]
I'm having the same issue (Tests continue even though there was an error) with `casperjs 1.1.0-beta3`. Never the less I think it would be nice to have an Option to have one profile that will continue running on errors and one that will stop on errors (might come in handy with CI).
