### ISSUE TITLE
error execvp(): No such file or directory

### ISSUE THREAD

**Issue by AlessandroMinoccheri** [ronaldlokers/grunt-casperjs#54]
Hi, I would like to launch casper test file from grunt. I have create a config file (config.js) with all my var, if I launch this command in shell it works fine:

```
casperjs test app/Test/Frontend/casper/**/*.js --includes=app/Test/Frontend/config.js
```

but if I use grunt-casperjs inside my gruntfile return me this error:

```
execvp(): No such file or directory
Fatal error: spawn ENOENT
```

This is my task in grunt:

```
      casperjs: {
            options: {
                casperjsOptions: ['--includes=app/Test/Frontend/config.js']
            },
            files: [
                'app/Test/Frontend/casper/**/*.js'
            ]
        },
```

how can I solve?

**Comment by abilbaotm** [comment]
Same issue and fixed by https://github.com/ronaldlokers/grunt-casperjs/issues/54#issuecomment-59510680

Thanks!
